apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-live
  labels:
    app: auction-live
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auction-live
  template:
    metadata:
      labels:
        app: auction-live
    spec:
      containers:
      - name: auction-live
        image: rishi9759/auction-live:latest
        ports:
        - containerPort: 8090
