version: "3.8"

services:
  auctionlive:
    build: .
    container_name: auctionlive-cont
    ports:
      - "8080"  # Exposes the container's 8080 port to a random host port
    environment:
      - NODE_ENV=production
    networks:
      - auction_network

networks:
  auction_network:
    driver: bridge
