apiVersion: v1
kind: Service
metadata:
  name: auction-live
  labels:
    app: auction-live
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30001
  selector:
    app: auction-live
